### ISSUE TITLE
Add flag or configuration for adding videos

### ISSUE THREAD

**Issue by mbruzek** [chuckbutler/lazychannel#5]
I have a video blog that I need to catch up on and need the ability to download videos from youtube.  This tool would really rock if you could provide a way to save alternate formats.  

I am not sure if a flag is the way to go here, because you might want audio and video on the same instantiation of the lazychannel.

Please consider the fix.

**Comment by chuckbutler** [comment]
@mbruzek  Hey Matt. I just pushed up a branch that supports this feature by refactoring the app config. Would you mind giving this a go and giving some feedback on the feature?

**Comment by chuckbutler** [comment]
Things to know about this:

Refactors the output directory config option as 2 sep options - which in reality bumps this into 1.0.0 territory as its not backwords compatible.

You now have sep. keys to implement on the config.yaml under the youtube channel, and it will mirror the following format:

```
settings:
    audiodir: ~/Music/lazychannel
    videodir: ~/Videos/lazychannel
    limit: 2
channels:
    youtube:
        audio:
            ArgoFoxCreativeCommons: UC56Qctnsu8wAyvzf4Yx6LIw
        video:
            LinuxMusicMaster: MusicMasterUnlimited
```

Note: Limits are still global, and the code will always assume audio unless the video key is implicitly parsed. So if you add another subkey of say.. `octopus` - it will default to processing it as audio. This is to help mitigate any issues from user error / future features.

This presently only effects the youtube channel (as its the only one implemented)
